packaging_format = 2

id = "flow"
name = "Flow"
description.en = "Visual programming interface"
description.fr = "Interface de programmation visuelle"

version = "1.0~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "MIT"
website = "https://www.totaljs.com/flow/"
admindoc = "https://docs.totaljs.com/flow10/"
code = "https://github.com/totaljs/flow"

[integration]
yunohost = ">= 11.1.13"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
